/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CottageFormController;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import model.Cottage;

/**
 *
 * @author User
 */
public class BookingCottageForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistrationForm
     */
    public BookingCottageForm() {
        initComponents();
        setUI();
        setDate();
        loadData();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsave = new keeptoo.KButton();
        btndelete = new keeptoo.KButton();
        btnupdate = new keeptoo.KButton();
        btnclear = new keeptoo.KButton();
        txtOid = new javax.swing.JTextField();
        txtCid = new javax.swing.JTextField();
        txtDin = new javax.swing.JTextField();
        txtDout = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sp2 = new javax.swing.JSpinner();
        sp1 = new javax.swing.JSpinner();
        cmbroom = new javax.swing.JComboBox<>();
        cmbcottage = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCottage = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking Cottage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(380, 380, 380))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Room Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Booking Order ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Customer ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("No of Adults");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Date IN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Date OUT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Select Cottage");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsave.setkAllowGradient(false);
        btnsave.setkBackGroundColor(new java.awt.Color(0, 123, 255));
        btnsave.setkHoverColor(new java.awt.Color(0, 80, 255));
        btnsave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 160, -1));

        btndelete.setText("Delete");
        btndelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btndelete.setkAllowGradient(false);
        btndelete.setkBackGroundColor(new java.awt.Color(220, 53, 69));
        btndelete.setkHoverColor(new java.awt.Color(190, 53, 69));
        btndelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 580, 160, -1));

        btnupdate.setText("Update");
        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnupdate.setkAllowGradient(false);
        btnupdate.setkBackGroundColor(new java.awt.Color(40, 167, 69));
        btnupdate.setkHoverColor(new java.awt.Color(40, 140, 69));
        btnupdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 160, -1));

        btnclear.setText("Clear");
        btnclear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear.setkAllowGradient(false);
        btnclear.setkBackGroundColor(new java.awt.Color(255, 193, 7));
        btnclear.setkHoverColor(new java.awt.Color(255, 173, 7));
        btnclear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 140, -1));

        txtOid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtOid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtOid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 223, 220, 30));

        txtCid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 220, 30));

        txtDin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 220, 30));

        txtDout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDout.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtDout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 220, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("No of Children");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 130, -1));

        sp2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(sp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 60, -1));

        sp1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 60, -1));

        cmbroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(cmbroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 220, -1));

        cmbcottage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbcottage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(cmbcottage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 220, -1));

        tblCottage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblCottage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BID", "CID", "Adults", "Child", "In", "Out", "Cottage", "Room No"
            }
        ));
        tblCottage.setOpaque(false);
        tblCottage.setSelectionBackground(new java.awt.Color(0, 102, 255));
        tblCottage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCottageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCottage);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCottageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCottageMouseClicked
        int selectedRow = tblCottage.getSelectedRow();
        txtOid.setText(tblCottage.getValueAt(selectedRow, 0).toString());
        txtCid.setText(tblCottage.getValueAt(selectedRow, 1).toString());
//        txtlname.setText(tblCottage.getValueAt(selectedRow, 2).toString());
//        txtnic.setText(tblCottage.getValueAt(selectedRow, 3).toString());
//        txtaddr.setText(tblCottage.getValueAt(selectedRow, 4).toString());
//        txttpno.setText(tblCottage.getValueAt(selectedRow, 5).toString());
//        txtemail.setText(tblCottage.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_tblCottageMouseClicked

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        Cottage cottage = new Cottage(
                txtOid.getText(), 
                txtCid.getText(), 
                sp1.getValue().toString(), 
                sp2.getValue().toString(), 
                txtDin.getText(), 
                txtDout.getText(), 
                cmbcottage.getSelectedItem().toString(), 
                cmbroom.getSelectedItem().toString()
        );
        

        try {
            if (new CottageFormController().uploadCottage(cottage)) {
                JOptionPane.showMessageDialog(this, "Data Saved!");
                btnClear();
                loadData();

            } else {
                JOptionPane.showMessageDialog(this, "Something went Wrong!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BookingCottageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String oid = txtOid.getText();
        try {
            if (new CottageFormController().deleteCottage(oid)) {
                JOptionPane.showMessageDialog(null, "Cottage Succesfully deleted");
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingCottageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingCottageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnclear;
    private keeptoo.KButton btndelete;
    private keeptoo.KButton btnsave;
    private keeptoo.KButton btnupdate;
    private javax.swing.JComboBox<String> cmbcottage;
    private javax.swing.JComboBox<String> cmbroom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sp1;
    private javax.swing.JSpinner sp2;
    private javax.swing.JTable tblCottage;
    private javax.swing.JTextField txtCid;
    private javax.swing.JTextField txtDin;
    private javax.swing.JTextField txtDout;
    private javax.swing.JTextField txtOid;
    // End of variables declaration//GEN-END:variables

        private void setUI() {
        tblCottage.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblCottage.getTableHeader().setOpaque(false);
        tblCottage.getTableHeader().setBackground(new Color(184, 14, 61));
        tblCottage.getTableHeader().setForeground(new Color(255, 255, 255));
        tblCottage.getTableHeader().setBorder(new LineBorder(Color.white));
        tblCottage.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        Color ivory = new Color(255, 255, 255);
        tblCottage.setOpaque(true);
        tblCottage.setFillsViewportHeight(true);
        tblCottage.setBackground(ivory);
    }

    private void setDate() {
        LocalDate date = LocalDate.now();        
        txtDin.setText(date.toString());
        txtDout.setText(date.toString());
    }

    private void btnClear() {
        
    }

    private void loadData() {
        try {
            List<Cottage> list = new CottageFormController().loadAllData();
            DefaultTableModel model = (DefaultTableModel) tblCottage.getModel();
            model.setRowCount(0);
            list.forEach((cottage) -> {
                model.addRow(new Object[]{cottage.getBid(), cottage.getCid(), cottage.getNoa(),
                    cottage.getNoc(), cottage.getDin(), cottage.getDout(), cottage.getCottage(),cottage.getRoom()});
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
