/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CustomerFormController;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import model.Customer;

/**
 *
 * @author User
 */
public class CustomerRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistrationForm
     */
    public CustomerRegistrationForm() {
        initComponents();
        loadData();
        setUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsave = new keeptoo.KButton();
        btndelete = new keeptoo.KButton();
        btnupdate = new keeptoo.KButton();
        btnclear = new keeptoo.KButton();
        txtemail = new javax.swing.JTextField();
        txtcid = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        txtaddr = new javax.swing.JTextField();
        txttpno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Registration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(350, 350, 350))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("E Mail");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Customer ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("First name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Last name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("TP Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnsave.setkAllowGradient(false);
        btnsave.setkBackGroundColor(new java.awt.Color(0, 123, 255));
        btnsave.setkHoverColor(new java.awt.Color(0, 80, 255));
        btnsave.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 160, -1));

        btndelete.setText("Delete");
        btndelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btndelete.setkAllowGradient(false);
        btndelete.setkBackGroundColor(new java.awt.Color(220, 53, 69));
        btndelete.setkHoverColor(new java.awt.Color(190, 53, 69));
        btndelete.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, 160, -1));

        btnupdate.setText("Update");
        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnupdate.setkAllowGradient(false);
        btnupdate.setkBackGroundColor(new java.awt.Color(40, 167, 69));
        btnupdate.setkHoverColor(new java.awt.Color(40, 140, 69));
        btnupdate.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 160, -1));

        btnclear.setText("Clear");
        btnclear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnclear.setkAllowGradient(false);
        btnclear.setkBackGroundColor(new java.awt.Color(255, 193, 7));
        btnclear.setkHoverColor(new java.awt.Color(255, 173, 7));
        btnclear.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 140, -1));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 270, 30));

        txtcid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtcid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 223, 270, 30));

        txtfname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtfname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 270, 30));

        txtlname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtlname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 270, 30));

        txtnic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 270, 30));

        txtaddr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtaddr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 270, 30));

        txttpno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttpno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttpno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 270, 30));

        tblCustomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "FName", "LName", "NIC", "Address", "Tp No", "Email"
            }
        ));
        tblCustomer.setOpaque(false);
        tblCustomer.setSelectionBackground(new java.awt.Color(0, 102, 255));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        Customer c1 = new Customer(
                txtcid.getText(),
                txtfname.getText(),
                txtlname.getText(),
                txtnic.getText(),
                txtaddr.getText(),
                txttpno.getText(),
                txtemail.getText()
        );

        try {
            if (new CustomerFormController().updateCustommer(c1)) {
                JOptionPane.showMessageDialog(this, "Data Updated!");
                btnClear();
                loadData();

            } else {
                JOptionPane.showMessageDialog(this, "Something went Wrong!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        Customer c = new Customer(
                txtcid.getText(),
                txtfname.getText(),
                txtlname.getText(),
                txtnic.getText(),
                txtaddr.getText(),
                txttpno.getText(),
                txtemail.getText()
        );

        try {
            if (new CustomerFormController().uploadCustommer(c)) {
                JOptionPane.showMessageDialog(this, "Data Saved!");
                btnClear();
                loadData();

            } else {
                JOptionPane.showMessageDialog(this, "Something went Wrong!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        btnClear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        int selectedRow = tblCustomer.getSelectedRow();
        txtcid.setText(tblCustomer.getValueAt(selectedRow, 0).toString());
        txtfname.setText(tblCustomer.getValueAt(selectedRow, 1).toString());
        txtlname.setText(tblCustomer.getValueAt(selectedRow, 2).toString());
        txtnic.setText(tblCustomer.getValueAt(selectedRow, 3).toString());
        txtaddr.setText(tblCustomer.getValueAt(selectedRow, 4).toString());
        txttpno.setText(tblCustomer.getValueAt(selectedRow, 5).toString());
        txtemail.setText(tblCustomer.getValueAt(selectedRow, 6).toString());
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

            String cid = txtcid.getText();
        try {
            if (new CustomerFormController().deleteCustomer(cid)) {
                JOptionPane.showMessageDialog(null, "Customer Succesfully deleted");
                txtaddr.setText("");
                txtcid.setText("");
                txtemail.setText("");
                txtfname.setText("");
                txtlname.setText("");
                txtnic.setText("");
                txttpno.setText("");
                loadData();
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CustomerRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnclear;
    private keeptoo.KButton btndelete;
    private keeptoo.KButton btnsave;
    private keeptoo.KButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtaddr;
    private javax.swing.JTextField txtcid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txttpno;
    // End of variables declaration//GEN-END:variables

    private void btnClear() {
        txtaddr.setText("");
        txtcid.setText("");
        txtemail.setText("");
        txtfname.setText("");
        txtlname.setText("");
        txtnic.setText("");
        txttpno.setText("");
        loadData();
    }

    private void loadData() {
        try {
            List<Customer> list = new CustomerFormController().loadAllData();
            DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();
            model.setRowCount(0);
            list.forEach((customer) -> {
                model.addRow(new Object[]{customer.getCid(), customer.getFname(), customer.getLname(),
                    customer.getNic(), customer.getAddr(), customer.getTp(), customer.getEmail()});
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setUI() {
        tblCustomer.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblCustomer.getTableHeader().setOpaque(false);
        tblCustomer.getTableHeader().setBackground(new Color(184, 14, 61));
        tblCustomer.getTableHeader().setForeground(new Color(255, 255, 255));
        tblCustomer.getTableHeader().setBorder(new LineBorder(Color.white));
        tblCustomer.setRowHeight(30);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        Color ivory = new Color(255, 255, 255);
        tblCustomer.setOpaque(true);
        tblCustomer.setFillsViewportHeight(true);
        tblCustomer.setBackground(ivory);
    }
}
